### PR TITLE
Support notice

### PR DESCRIPTION
**Pull request by sonots**
Added `identifier` option to support `notice`

### CODE REVIEW

**Comment by sonots** [comment]
If you prefer another option name, please let me know.

**Comment by choplin** [comment]
Thank you @sonots! How about `command` for its option name? According to the RFC, `PRIVMSG` and `NOTICE` are categorized as command. http://tools.ietf.org/html/rfc1459#section-4.4

**Comment by sonots** [comment]
Okay, I will change to command

**Comment by sonots** [comment]
Updated to `command`

**Comment by choplin** [comment]
Thank you!

**Pull request merged**
